src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank (message="ce champ doit etre remplie")
     */
    private $nom_categorie;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="La description est necessaire")
     *
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="categories")
     */
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setCategories($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategories() === $this) {
                $produit->setCategories(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
return $this->nom_categorie;    }


}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_categorie',\Symfony\Component\Form\Extension\Core\Type\TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ]
            ])
            ->add('description',\Symfony\Component\Form\Extension\Core\Type\TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;

use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class CategorieController extends AbstractController
{
    /**
     * @Route("/categorie", name="categorie")
     */
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/listecategorie.html.twig', [
            'categories' => $categorieRepository->FindAll(),

        ]);
    }

    /**
     * @Route("categorie/{id}/show", name="categorie_show")
     * @param Categorie $categorie
     * @return Response
     */
    public function show(Categorie $categorie): Response
    {
        return $this->render("categorie/show.html.twig", [
            "categorie" => $categorie
        ]);
    }
    /**
     * @Route("categorie/add", name="categorie_add")
     * @param Request $request
     * @return Response
     */
    public function add(Request $request): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($categorie);
            $em->flush();

            return $this->redirectToRoute('categorie');

        }
        return $this->render('categorie/add.html.twig', [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("categorie/{id}/edit", name="categorie_edit")
     * @param Categorie $categorie
     * @param Request $request
     * @return Response
     */
    public function edit(Categorie $categorie, Request $request): Response
    {
        $form = $this->createForm(CategorieType::class,$categorie);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('categorie');
        }
        return $this->render("categorie/edit.html.twig", [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("categorie/{id}/delete", name="categorie_delete")
     * @param Categorie $categorie
     * @return RedirectResponse
     */
    public function delete(Categorie $categorie): RedirectResponse
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($categorie);
        $em->flush();

        return $this->redirectToRoute("categorie");
    }

}

templates/categorie/_form.html.twig
<div class="card">
    <div class="card-body">
          <h4 class="card-title">Ajout Categorie </h4>


        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
            <div class="form-group" >
                <label>Nom Categorie</label>

                    {{ form_widget(form.nom_categorie) }}
                    {{ form_errors(form.nom_categorie) }}

            </div>
            <div class="form-group">
                <label>Description</label>
                {{ form_widget(form.description) }}
                {{ form_errors(form.description) }}
            </div>

templates/categorie/add.html.twig
{% extends 'base-back.html.twig' %}

{% block title %} Ajouter Categorie {% endblock %}

{% block body %}

    <h1>Ajouter une categorie </h1>


    {{ include('categorie/_form.html.twig') }}
    <button type="submit" class="btn btn-primary mr-2">Ajouter </button>
    <button class="btn btn-dark">Cancel</button>
    {{ form_rest(form) }}
    {{ form_end(form) }}
    </form>
    </div>
    </div>
{% endblock %}

templates/categorie/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %} Editer Categorie {% endblock %}

{% block body %}

    <h1>Editer Categorie </h1>

    {{ form_start(form) }}

    {{ include('categorie/_form.html.twig') }}
    <button type="submit" class="btn btn-primary mr-2">Editer </button>
    <button class="btn btn-dark">Cancel</button>
    {{ form_rest(form) }}
    {{ form_end(form) }}
    </form>
    </div>
    </div>
{% endblock %}

templates/categorie/listecategorie.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}
{% endblock %}

{% block body %}



    <div class="card-body">
        <h4 class="card-title">Liste Des Categories</h4>


        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th> Id </th>
                    <th> Nom Categorie </th>
                    <th> Description </th>
                    <th> Action </th>

                </tr>
                </thead>
                <tbody>
                {% for categorie in categories %}
                    <tr>
                        <td class="py-1">
                            {{ categorie.id }}
                        </td>
                        <td> {{ categorie.nomCategorie }} </td>
                        <td>  {{ categorie.description }}</td>
                        <td>
                            <a href="{{ path('categorie_edit', {'id': categorie.id}) }}">Modifier</a>
                            <a href="{{ path('categorie_delete', {'id': categorie.id}) }}">Supprimer</a>
                            <a href="{{ path('categorie_add') }}">Ajouter</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">no records found</td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>





{% endblock %}

templates/categorie/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}


    <div class="card-body">
        <h4 class="card-title">Liste Des Categories</h4>


        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th> Id </th>
                    <th> Nom categorie </th>
                    <th> Description </th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="py-1">
                        {{ categorie.id }}
                    </td>
                    <td> {{ categorie.nomCategorie }} </td>
                    <td>  {{ categorie.description }}</td>


                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-2.png" alt="image">
                    </td>
                    <td> Messsy Adam </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $245.30 </td>
                    <td> July 1, 2015 </td>
                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-3.png" alt="image">
                    </td>
                    <td> John Richards </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $138.00 </td>
                    <td> Apr 12, 2015 </td>
                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-4.png" alt="image">
                    </td>
                    <td> Peter Meggik </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-primary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $ 77.99 </td>
                    <td> May 15, 2015 </td>
                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-1.png" alt="image">
                    </td>
                    <td> Edward </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-danger" role="progressbar" style="width: 35%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $ 160.25 </td>
                    <td> May 03, 2015 </td>
                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-2.png" alt="image">
                    </td>
                    <td> John Doe </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $ 123.21 </td>
                    <td> April 05, 2015 </td>
                </tr>
                <tr>
                    <td class="py-1">
                        <img src="../../assets/images/faces-clipart/pic-3.png" alt="image">
                    </td>
                    <td> Henry Tom </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </td>
                    <td> $ 150.00 </td>
                    <td> June 16, 2015 </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>





{% endblock %}